from neurolab import params as P
import params as PP


config_gdes = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.model_6l.Net',
	P.KEY_NET_OUTPUTS: 'fc6',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.CrossEntMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, # 0.1,
    P.KEY_MILESTONES: range(10, 20), # [20, 30],
    P.KEY_MOMENTUM: 0.9,
    P.KEY_L2_PENALTY: 5e-2,
	P.KEY_DROPOUT_P: 0.5,
	P.KEY_HPMANAGER: 'neurolab.hpsearch.DiscAltMinHPManager',
	P.KEY_HPSEARCH_PARAMS: {P.KEY_LEARNING_RATE: [1e-2, 1e-3, 1e-4], P.KEY_L2_PENALTY: [5e-2, 5e-3, 5e-4]},
}

config_hebb = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.hebb.model_2l.Net',
	P.KEY_NET_OUTPUTS: 'fc2',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None, #2,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
	P.KEY_LOCAL_LRN_RULE: 'hpca', #'hwta',
	#PP.KEY_WTA_COMPETITIVE_ACT: 'hebb.functional.kwta',
	#PP.KEY_WTA_K: 1,
}

config_ica = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.hebb.model_2l.Net',
	P.KEY_NET_OUTPUTS: 'fc2',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
	P.KEY_LOCAL_LRN_RULE: 'ica',
	PP.KEY_ICA_ACT_COMPLEMENT_INIT: 'act_complement_init_splt',
	PP.KEY_ICA_ACT_COMPLEMENT_RATIO: 0.,
	PP.KEY_ICA_ACT_COMPLEMENT_ADAPT: None,
	PP.KEY_ICA_ACT_COMPLEMENT_GRP: False,
	PP.KEY_ACT_LAMB: 1.,
}

config_vae = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.AEVisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.vae_6l.Net',
	P.KEY_NET_OUTPUTS: 'vae_output',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.ELBOMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.ELBOMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, #0.1,
    P.KEY_MILESTONES: range(10, 20), #[20, 30],
    P.KEY_MOMENTUM: 0.9,
	P.KEY_ELBO_BETA: .5,
}

fc_on_gdes_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.fc.Net',
	P.KEY_NET_OUTPUTS: 'fc',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.CrossEntMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, #0.1,
    P.KEY_MILESTONES: range(10, 20), #[20, 30],
    P.KEY_MOMENTUM: 0.9,
    P.KEY_L2_PENALTY: 5e-4,
	P.KEY_DROPOUT_P: 0.5,
	P.KEY_PRE_NET_MODULES: ['models.gdes.model_2l.Net'],
	P.KEY_PRE_NET_MDL_PATHS: [P.PROJECT_ROOT + '/results/configs/base/config_gdes/iter' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_PRE_NET_OUTPUTS: ['bn1'],
}

fc_on_hebb_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.fc.Net',
	P.KEY_NET_OUTPUTS: 'fc',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: 2,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.CrossEntMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, #0.1,
    P.KEY_MILESTONES: range(10, 20), #[20, 30],
    P.KEY_MOMENTUM: 0.9,
    P.KEY_L2_PENALTY: 5e-4,
	P.KEY_DROPOUT_P: 0.5,
	P.KEY_LOCAL_LRN_RULE: 'hwta',
	PP.KEY_WTA_COMPETITIVE_ACT: 'hebb.functional.kwta',
	PP.KEY_WTA_K: 1,
	P.KEY_PRE_NET_MODULES: ['models.hebb.model_2l.Net'],
	P.KEY_PRE_NET_MDL_PATHS: [P.PROJECT_ROOT + '/results/configs/base/config_hebb/iter' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_PRE_NET_OUTPUTS: ['bn1'],
}

sk_on_gdes_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'neurolab.model.skclassif.KNNClassifier',
	P.KEY_NET_OUTPUTS: 'clf',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 1, #2,
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
	P.KEY_SKCLF_NUM_SAMPLES: 40000, #80000,
	P.KEY_NYSTROEM_N_COMPONENTS: 100,
	P.KEY_KNN_N_NEIGHBORS: 10,
	P.KEY_PRE_NET_MODULES: ['models.gdes.model_2l.Net'],
	P.KEY_PRE_NET_MDL_PATHS: [P.PROJECT_ROOT + '/results/configs/base/config_gdes/iter' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_PRE_NET_OUTPUTS: ['bn1'],
}

btmupexp_fc_on_gdes_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.btmupexp.BtmUpExperiment',
	P.KEY_SUBCONFIG_LIST: ['configs.base.config_gdes', 'configs.base.fc_on_gdes_layer'],
	'exp0+exp1::' + P.KEY_NUM_EPOCHS: 2,
	'exp0+exp1::' + P.KEY_LEARNING_RATE: 1e-3,
	'exp0::' + P.KEY_L2_PENALTY: 5e-2,
	'exp1::' + P.KEY_L2_PENALTY: 5e-4,
	'exp1::' + P.KEY_PRE_NET_MDL_PATHS: ['exp0/iter' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_HPMANAGER: 'neurolab.hpsearch.DiscAltMinHPManager',
	P.KEY_HPSEARCH_PARAMS: {'exp0+exp1::' + P.KEY_LEARNING_RATE: [1e-4, 1e-3], 'exp0::' + P.KEY_L2_PENALTY: [5e-2, 5e-3, 5e-4], 'exp1::' + P.KEY_L2_PENALTY: [5e-2, 5e-3, 5e-4]},
}


config_stackvae = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.stackvae_6l.Net',
	P.KEY_NET_OUTPUTS: 'fc6',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.CrossEntMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, #0.1,
    P.KEY_MILESTONES: range(10, 20), #[20, 30],
    P.KEY_MOMENTUM: 0.9,
	P.KEY_ELBO_BETA: .5,
	P.KEY_ALPHA: 1.,
}

fc_on_stackvae_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.fc.Net',
	P.KEY_NET_OUTPUTS: 'fc',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.CrossEntMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, #0.1,
    P.KEY_MILESTONES: range(10, 20), #[20, 30],
    P.KEY_MOMENTUM: 0.9,
    P.KEY_L2_PENALTY: 5e-4,
	P.KEY_DROPOUT_P: 0.5,
	P.KEY_PRE_NET_MODULES: ['models.gdes.stackvae_6l.Net'],
	P.KEY_PRE_NET_MDL_PATHS: [P.PROJECT_ROOT + '/results/configs/base/config_stackvae/iter' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_PRE_NET_OUTPUTS: ['bn5'],
	P.KEY_ELBO_BETA: .5,
	P.KEY_ALPHA: 0.,
}

btmupexp_fc_on_stackvae_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.btmupexp.BtmUpExperiment',
	P.KEY_SUBCONFIG_LIST: ['configs.base.config_stackvae', 'configs.base.fc_on_stackvae_layer'],
	'exp0+exp1::' + P.KEY_ELBO_BETA: 0.5,
	'exp1::' + P.KEY_PRE_NET_MDL_PATHS: ['exp0/iter' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_HPMANAGER: 'neurolab.hpsearch.DiscAltMinHPManager',
	P.KEY_HPSEARCH_PARAMS: {'exp0+exp1::' + P.KEY_ELBO_BETA: [0., .1, .5, .9, 1.]},
}
